steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/novivet:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/novivet:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/novivet:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/novivet:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'novivet'
      - '--image'
      - 'gcr.io/$PROJECT_ID/novivet:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
images:
  - 'gcr.io/$PROJECT_ID/novivet:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/novivet:latest'
timeout: '1200s'
